services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    restart: unless-stopped
    environment:
      MONGO_URI: "mongodb://mongo:27017/assetdb"
      PORT: "4000"
      CORS_ORIGIN: "*"
      JWT_SECRET: "devsecret_change_me"
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - server-uploads:/app/uploads

volumes:
  mongo-data:
  server-uploads:
