services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    restart: unless-stopped
    environment:
      MONGO_URI: "${MONGO_URI:-mongodb://mongo:27017/assetdb}"
      PORT: "${API_PORT:-4000}"
      CORS_ORIGIN: "${CORS_ORIGIN:-*}"
      JWT_SECRET: "${JWT_SECRET:-devsecret_change_me}"
    ports:
      - "${API_PORT:-4000}:4000"
    depends_on:
      - mongo
    volumes:
      - server-uploads:/app/uploads

  client:
    build:
      context: ./client
      args:
        # Vite reads this at build time
        VITE_API_BASE: "${VITE_API_BASE:-http://localhost:4000}"
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-8080}:80"
    depends_on:
      - server

volumes:
  mongo-data:
  server-uploads:
