version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  server:
    image: assetdb-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      MONGO_URL: "mongodb://mongo:27017/assetdb"
      JWT_SECRET: "change-me-in-prod"
      PORT: "4000"
      # Registration guarded in code; default is off.
      ENABLE_REGISTRATION: "0"
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    restart: unless-stopped

  client:
    image: assetdb-client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE: "/api"
    depends_on:
      - server
    ports:
      - "8080:80"   # use "80:80" if you want no port in URL
    restart: unless-stopped

networks:
  default:
    name: assetdb_default
