services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: assetdb-server
    environment:
      MONGO_URL: "mongodb://mongo:27017/assetdb"
      JWT_SECRET: "change-me-in-prod"
      PORT: "4000"
      ENABLE_REGISTRATION: "0"   # flip to "1" temporarily to self-register
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: assetdb-client
    environment:
      VITE_API_BASE: "/api"
    depends_on:
      - server
    ports:
      - "80:80"
    restart: unless-stopped

networks:
  default:
    name: assetdb_default
