 name: CI
-on:
-  push:
-  pull_request:
+on:
+  push:
+  pull_request:
+  workflow_dispatch: {}

 permissions:
   contents: read

 jobs:
   build-and-test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4

-      # -------- Node 20 for everything --------
-      - uses: actions/setup-node@v4
-        with:
-          node-version: '20'
-          cache: 'npm'
+      # -------- Node 20 with cache if any lockfile exists --------
+      - name: Setup Node (cached)
+        if: |
+          hashFiles('package-lock.json') != '' ||
+          hashFiles('yarn.lock') != '' ||
+          hashFiles('npm-shrinkwrap.json') != '' ||
+          hashFiles('server/package-lock.json') != '' ||
+          hashFiles('server/yarn.lock') != '' ||
+          hashFiles('server/npm-shrinkwrap.json') != '' ||
+          hashFiles('client/package-lock.json') != '' ||
+          hashFiles('client/yarn.lock') != '' ||
+          hashFiles('client/npm-shrinkwrap.json') != ''
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20'
+          cache: npm
+          cache-dependency-path: |
+            package-lock.json
+            npm-shrinkwrap.json
+            yarn.lock
+            server/package-lock.json
+            server/npm-shrinkwrap.json
+            server/yarn.lock
+            client/package-lock.json
+            client/npm-shrinkwrap.json
+            client/yarn.lock
+
+      # -------- Node 20 without cache if no lockfiles but package.json exists --------
+      - name: Setup Node (no cache)
+        if: |
+          (hashFiles('package.json') != '' ||
+           hashFiles('server/package.json') != '' ||
+           hashFiles('client/package.json') != '') &&
+          (hashFiles('package-lock.json') == '' &&
+           hashFiles('yarn.lock') == '' &&
+           hashFiles('npm-shrinkwrap.json') == '' &&
+           hashFiles('server/package-lock.json') == '' &&
+           hashFiles('server/yarn.lock') == '' &&
+           hashFiles('server/npm-shrinkwrap.json') == '' &&
+           hashFiles('client/package-lock.json') == '' &&
+           hashFiles('client/yarn.lock') == '' &&
+           hashFiles('client/npm-shrinkwrap.json') == '')
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20'
